services:
  db:
    image: postgres:latest # You can specify a different version like postgres:14-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data to a named volume

volumes:
  pgdata: # Define the named volume for data persistence

